### ISSUE TITLE
Icons and Images not showing

### ISSUE THREAD

**Issue by atifjkhan** [dimaportenko/magento-react-native-community#2]
![image](https://user-images.githubusercontent.com/53400712/113505833-d909ae00-9573-11eb-83aa-2b2c0b0942cd.png)
Here is my config file and yes i setup my Magento on local

My only error when i run says:
` WARN  Easing was renamed to EasingNode in Reanimated 2. Please use EasingNode instead`

And my android emulator looks like this:
![image](https://user-images.githubusercontent.com/53400712/113505918-3dc50880-9574-11eb-8e05-7dfc0ab5796a.png)
![image](https://user-images.githubusercontent.com/53400712/113505925-49b0ca80-9574-11eb-95ba-3f62a640766b.png)

if i missed any detail pls tell me ill try to give you more details
Thanks for your help in advance!

**Comment by dimaportenko** [comment]
@atifjkhan can you reproduce this issue with the config?
```
module.exports = {
  magentoConfig: {
    url: 'https://master-7rqtwti-mfwmkrjfqvbjk.us-4.magentosite.cloud/',
  },
};
```
